/* fstab.c - 2O9 declarative /etc/fstab management
 *
 * Reads fileSystems and swapDevices from the manifest JSON (the
 * evaluated 2O9.nix) and generates /etc/fstab on 209 apply. Creates swap
 * files declared with a size (dd + chmod 0600 + mkswap). Backs up the
 * previous /etc/fstab to /etc/fstab.bak.2O9 (single most-recent backup).
 * When the generated content differs from the existing fstab, runs
 * `swapon -a` and `mount -a`. mount -a does not remount already-mounted
 * file systems, so option changes need a reboot; we print a note.
 *
 * For each file system removed between the previous and current
 * manifests, prints a warning naming the mount point and the device it
 * used to be on. Nothing is unmounted or destroyed.
 *
 * The Makefile already passes -D_GNU_SOURCE; open_memstream / asprintf /
 * strndup are available because of that.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <errno.h>
#include <limits.h>

#include "fstab.h"
#include "cJSON.h"

#define FSTAB_PATH     "/etc/fstab"
#define FSTAB_BAK_PATH "/etc/fstab.bak.2O9"
#define FSTAB_HEADER   "# Generated by 2O9. Do not edit; run `209 apply` to regenerate.\n"

/* ── Helpers ─────────────────────────────────────────────────────────── */

/* Number of '/' chars in p, used as the sort key so shallower mounts
 * come first. "/" -> 1, "/boot" -> 2, "/home/rui/data" -> 4. */
static int path_depth(const char *p)
{
    int n = 0;
    for (const char *c = p; *c; c++)
        if (*c == '/') n++;
    return n;
}

/* fsck pass: / -> 1, /boot and /boot/... and /efi and /efi/... -> 2,
 * everything else -> 0. dump pass: / -> 1, everything else -> 0. */
static int fsck_pass_for(const char *mount)
{
    if (strcmp(mount, "/") == 0) return 1;
    if (strncmp(mount, "/boot", 5) == 0 &&
        (mount[5] == '\0' || mount[5] == '/')) return 2;
    if (strncmp(mount, "/efi", 4) == 0 &&
        (mount[4] == '\0' || mount[4] == '/')) return 2;
    return 0;
}

static int dump_pass_for(const char *mount)
{
    return strcmp(mount, "/") == 0 ? 1 : 0;
}

/* Comma-join a cJSON options array. Defaults to "defaults" when the
 * array is missing or empty. Returns a malloc'd string or NULL on OOM. */
static char *join_options(cJSON *options)
{
    if (!options || !cJSON_IsArray(options) || cJSON_GetArraySize(options) == 0)
        return strdup("defaults");

    size_t need = 1;
    cJSON *opt;
    cJSON_ArrayForEach(opt, options) {
        if (cJSON_IsString(opt)) need += strlen(opt->valuestring) + 1;
    }
    if (need == 1) return strdup("defaults");

    char *buf = malloc(need);
    if (!buf) return NULL;
    buf[0] = '\0';
    int first = 1;
    cJSON_ArrayForEach(opt, options) {
        if (cJSON_IsString(opt)) {
            if (!first) strcat(buf, ",");
            strcat(buf, opt->valuestring);
            first = 0;
        }
    }
    return buf;
}

/* Run a subprocess via fork+execvp. Returns the exit status (0 on
 * success), or -1 on fork/wait failure. Exit 127 means "binary not
 * found" - callers report it themselves. */
static int run_cmd(const char *argv[])
{
    pid_t pid = fork();
    if (pid < 0) { perror("fork"); return -1; }
    if (pid == 0) {
        execvp(argv[0], (char *const *)argv);
        _exit(127);
    }
    int status = 0;
    if (waitpid(pid, &status, 0) < 0) { perror("waitpid"); return -1; }
    if (WIFEXITED(status)) return WEXITSTATUS(status);
    return -1;
}

/* Read an entire file into a malloc'd buffer. Returns NULL if the file
 * doesn't exist or can't be read. Caller frees. */
static char *read_file(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return NULL; }
    rewind(f);
    char *buf = malloc((size_t)sz + 1);
    if (!buf) { fclose(f); return NULL; }
    size_t n = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    buf[n] = '\0';
    return buf;
}

/* Find the root ("/") entry in an existing fstab and return it as a
 * freshly-formatted "<dev> / <fstype> <options> <dump> <pass>\n" line.
 * Used when the manifest declares no fileSystems so we keep the root
 * mount working. Returns NULL if no root entry is found. Caller frees. */
static char *extract_root_from_existing(const char *existing)
{
    if (!existing) return NULL;
    const char *line = existing;
    while (*line) {
        const char *eol = strchr(line, '\n');
        size_t linelen = eol ? (size_t)(eol - line) : strlen(line);

        size_t start = 0;
        while (start < linelen &&
               (line[start] == ' ' || line[start] == '\t'))
            start++;
        if (start >= linelen || line[start] == '#') {
            if (!eol) break;
            line = eol + 1;
            continue;
        }

        char *copy = strndup(line + start, linelen - start);
        if (!copy) { if (!eol) break; line = eol + 1; continue; }

        char *sp = NULL;
        char *t_dev  = strtok_r(copy, " \t", &sp);
        char *t_mnt  = t_dev  ? strtok_r(NULL, " \t", &sp) : NULL;
        char *t_type = t_mnt  ? strtok_r(NULL, " \t", &sp) : NULL;
        char *t_opt  = t_type ? strtok_r(NULL, " \t", &sp) : NULL;
        char *t_dump = t_opt  ? strtok_r(NULL, " \t", &sp) : NULL;
        char *t_pass = t_dump ? strtok_r(NULL, " \t", &sp) : NULL;

        char *out = NULL;
        if (t_mnt && strcmp(t_mnt, "/") == 0) {
            if (asprintf(&out, "%s / %s %s %s %s\n",
                         t_dev   ? t_dev   : "",
                         t_type  ? t_type  : "auto",
                         t_opt   ? t_opt   : "defaults",
                         t_dump  ? t_dump  : "1",
                         t_pass  ? t_pass  : "1") < 0) {
                free(copy);
                return NULL;
            }
            free(copy);
            return out;
        }
        free(copy);
        if (!eol) break;
        line = eol + 1;
    }
    return NULL;
}

/* ── fileSystem entry collection ─────────────────────────────────────── */

typedef struct {
    char *mount;
    char *device;
    char *fstype;
    char *options;
    int   dump;
    int   pass;
} fs_entry_t;

static int fs_entry_cmp(const void *a, const void *b)
{
    const fs_entry_t *ea = a, *eb = b;
    int da = path_depth(ea->mount);
    int db = path_depth(eb->mount);
    if (da != db) return da - db;
    return strcmp(ea->mount, eb->mount);
}

static void fs_entry_free(fs_entry_t *e, size_t n)
{
    for (size_t i = 0; i < n; i++) {
        free(e[i].mount);
        free(e[i].device);
        free(e[i].fstype);
        free(e[i].options);
    }
    free(e);
}

/* True when p is a block-device path under /dev/ (covers /dev/sda1,
 * /dev/disk/by-uuid/..., /dev/disk/by-label/...). */
static int is_block_device_path(const char *p)
{
    return strncmp(p, "/dev/", 5) == 0;
}

/* Create a swap file at <path> of <size> MB. If the file already exists
 * with the right size, no-op. If it exists with a different size, warn
 * and skip. Returns 0 on success or graceful skip, non-zero on error. */
static int create_swap_file(const char *path, long size, int dry_run)
{
    struct stat st;
    if (stat(path, &st) == 0) {
        long existing_mb = (long)(st.st_size / (1024L * 1024L));
        if (existing_mb == size) {
            printf("fstab: swap file %s already %ld MB, skipping creation\n",
                   path, size);
            return 0;
        }
        fprintf(stderr, "fstab: WARNING swap file %s exists but is %ld MB "
                "(expected %ld MB); leaving it in place\n",
                path, existing_mb, size);
        return 0;
    }

    if (dry_run) {
        printf("fstab: [dry-run] would create swap file %s (%ld MB)\n",
               path, size);
        return 0;
    }

    printf("fstab: creating swap file %s (%ld MB)\n", path, size);
    char *of_arg = NULL, *count_arg = NULL;
    if (asprintf(&of_arg, "of=%s", path) < 0 || !of_arg) {
        free(of_arg);
        return -1;
    }
    if (asprintf(&count_arg, "count=%ld", size) < 0 || !count_arg) {
        free(of_arg); free(count_arg);
        return -1;
    }
    const char *dd_argv[] = {"dd", "if=/dev/zero", of_arg,
                             "bs=1M", count_arg, NULL};
    int rc = run_cmd(dd_argv);
    free(of_arg);
    free(count_arg);
    if (rc != 0) {
        fprintf(stderr, "fstab: dd failed for %s (exit %d)\n", path, rc);
        return rc;
    }

    if (chmod(path, 0600) != 0) {
        fprintf(stderr, "fstab: chmod 0600 %s failed: %s\n",
                path, strerror(errno));
        return -1;
    }

    const char *mkswap_argv[] = {"mkswap", path, NULL};
    rc = run_cmd(mkswap_argv);
    if (rc != 0) {
        fprintf(stderr, "fstab: mkswap %s failed (exit %d)\n", path, rc);
        return rc;
    }
    return 0;
}

/* ── Main entry point ────────────────────────────────────────────────── */

int fstab_apply(const char *manifest_json, const char *prev_manifest_json,
                int dry_run)
{
    if (getuid() != 0) {
        fprintf(stderr, "fstab: must run as root (writes /etc/fstab, "
                "runs mount/swapon/mkswap)\n");
        return 1;
    }
    if (!manifest_json) {
        fprintf(stderr, "fstab: manifest_json is NULL\n");
        return 1;
    }

    cJSON *root = cJSON_Parse(manifest_json);
    if (!root) {
        fprintf(stderr, "fstab: failed to parse manifest JSON\n");
        return 1;
    }
    cJSON *prev_root = NULL;
    if (prev_manifest_json) {
        prev_root = cJSON_Parse(prev_manifest_json);
        /* NULL is OK - we just skip the prev comparison. */
    }

    /* ── Collect fileSystem entries ────────────────────────────────── */
    cJSON *fs_obj = cJSON_GetObjectItem(root, "fileSystems");
    fs_entry_t *entries = NULL;
    size_t n_entries = 0, cap_entries = 0;

    if (fs_obj && cJSON_IsObject(fs_obj)) {
        cJSON *entry;
        cJSON_ArrayForEach(entry, fs_obj) {
            if (!cJSON_IsObject(entry)) continue;
            if (!entry->string || entry->string[0] == '\0') continue;

            cJSON *dev = cJSON_GetObjectItem(entry, "device");
            cJSON *typ = cJSON_GetObjectItem(entry, "fsType");
            cJSON *opt = cJSON_GetObjectItem(entry, "options");
            if (!cJSON_IsString(dev) || !cJSON_IsString(typ)) {
                fprintf(stderr, "fstab: skipping malformed fileSystem entry "
                        "for %s (device and fsType required)\n",
                        entry->string ? entry->string : "?");
                continue;
            }

            if (n_entries == cap_entries) {
                cap_entries = cap_entries ? cap_entries * 2 : 8;
                fs_entry_t *grown = realloc(entries,
                                            cap_entries * sizeof(*entries));
                if (!grown) {
                    fprintf(stderr, "fstab: out of memory\n");
                    fs_entry_free(entries, n_entries);
                    cJSON_Delete(root);
                    cJSON_Delete(prev_root);
                    return 1;
                }
                entries = grown;
            }

            fs_entry_t *e = &entries[n_entries];
            e->mount   = strdup(entry->string);
            e->device  = strdup(dev->valuestring);
            e->fstype  = strdup(typ->valuestring);
            e->options = join_options(opt);
            e->dump    = dump_pass_for(e->mount);
            e->pass    = fsck_pass_for(e->mount);
            if (!e->mount || !e->device || !e->fstype || !e->options) {
                fprintf(stderr, "fstab: out of memory\n");
                fs_entry_free(entries, n_entries + 1);
                cJSON_Delete(root);
                cJSON_Delete(prev_root);
                return 1;
            }
            n_entries++;
        }
    }

    if (n_entries > 1)
        qsort(entries, n_entries, sizeof(*entries), fs_entry_cmp);

    /* ── Collect swapDevices and create swap files if needed ───────── */
    cJSON *swap_arr = cJSON_GetObjectItem(root, "swapDevices");
    char **swap_lines = NULL;
    size_t n_swap = 0, cap_swap = 0;

    if (swap_arr && cJSON_IsArray(swap_arr)) {
        cJSON *sw;
        cJSON_ArrayForEach(sw, swap_arr) {
            if (!cJSON_IsObject(sw)) continue;
            cJSON *dev = cJSON_GetObjectItem(sw, "device");
            cJSON *sz  = cJSON_GetObjectItem(sw, "size");
            if (!cJSON_IsString(dev)) {
                fprintf(stderr, "fstab: skipping malformed swapDevice "
                        "(device required)\n");
                continue;
            }
            const char *devpath = dev->valuestring;
            if (cJSON_IsNumber(sz) && !is_block_device_path(devpath)) {
                long size_mb = (long)sz->valuedouble;
                if (create_swap_file(devpath, size_mb, dry_run) != 0) {
                    fprintf(stderr, "fstab: swap file creation failed for "
                            "%s; skipping fstab entry\n", devpath);
                    continue;
                }
            }

            if (n_swap == cap_swap) {
                cap_swap = cap_swap ? cap_swap * 2 : 4;
                char **grown = realloc(swap_lines,
                                       cap_swap * sizeof(*swap_lines));
                if (!grown) {
                    fprintf(stderr, "fstab: out of memory\n");
                    for (size_t i = 0; i < n_swap; i++) free(swap_lines[i]);
                    free(swap_lines);
                    fs_entry_free(entries, n_entries);
                    cJSON_Delete(root);
                    cJSON_Delete(prev_root);
                    return 1;
                }
                swap_lines = grown;
            }
            char *line = NULL;
            if (asprintf(&line, "%s none swap defaults 0 0\n", devpath) < 0
                || !line) {
                fprintf(stderr, "fstab: out of memory\n");
                for (size_t i = 0; i < n_swap; i++) free(swap_lines[i]);
                free(swap_lines);
                fs_entry_free(entries, n_entries);
                cJSON_Delete(root);
                cJSON_Delete(prev_root);
                return 1;
            }
            swap_lines[n_swap++] = line;
        }
    }

    /* ── Warn about removed file systems ───────────────────────────── */
    if (prev_root) {
        cJSON *prev_fs = cJSON_GetObjectItem(prev_root, "fileSystems");
        if (prev_fs && cJSON_IsObject(prev_fs)) {
            cJSON *entry;
            cJSON_ArrayForEach(entry, prev_fs) {
                if (!entry->string) continue;
                int still_present = 0;
                for (size_t i = 0; i < n_entries; i++) {
                    if (strcmp(entries[i].mount, entry->string) == 0) {
                        still_present = 1;
                        break;
                    }
                }
                if (!still_present) {
                    cJSON *dev = cJSON_GetObjectItem(entry, "device");
                    fprintf(stderr, "fstab: WARNING file system %s no longer "
                            "declared (was mounted on %s); fstab line "
                            "removed. Unmount manually if needed.\n",
                            entry->string,
                            (dev && cJSON_IsString(dev))
                                ? dev->valuestring : "(unknown device)");
                }
            }
        }
    }

    /* ── Build the new fstab content via open_memstream ────────────── */
    char *content = NULL;
    size_t content_len = 0;
    FILE *mem = open_memstream(&content, &content_len);
    if (!mem) {
        fprintf(stderr, "fstab: open_memstream failed\n");
        for (size_t i = 0; i < n_swap; i++) free(swap_lines[i]);
        free(swap_lines);
        fs_entry_free(entries, n_entries);
        cJSON_Delete(root);
        cJSON_Delete(prev_root);
        return 1;
    }

    fputs(FSTAB_HEADER, mem);

    if (n_entries == 0) {
        /* No fileSystems declared. Keep the existing root entry if we
         * can find one so the box still boots. */
        char *existing = read_file(FSTAB_PATH);
        char *root_line = extract_root_from_existing(existing);
        free(existing);
        if (root_line) {
            fputs(root_line, mem);
            free(root_line);
        } else {
            fprintf(stderr, "fstab: WARNING no fileSystems declared and no "
                    "existing root entry in /etc/fstab; fstab will only "
                    "contain swap entries\n");
        }
    } else {
        for (size_t i = 0; i < n_entries; i++) {
            fprintf(mem, "%s %s %s %s %d %d\n",
                    entries[i].device, entries[i].mount, entries[i].fstype,
                    entries[i].options, entries[i].dump, entries[i].pass);
        }
    }

    for (size_t i = 0; i < n_swap; i++) fputs(swap_lines[i], mem);

    fclose(mem);

    for (size_t i = 0; i < n_swap; i++) free(swap_lines[i]);
    free(swap_lines);
    fs_entry_free(entries, n_entries);
    cJSON_Delete(root);
    cJSON_Delete(prev_root);

    /* ── Compare against existing fstab, then write or skip ────────── */
    char *existing = read_file(FSTAB_PATH);
    int changed = 1;
    if (existing && strcmp(existing, content) == 0) changed = 0;

    if (dry_run) {
        if (changed) {
            printf("fstab: [dry-run] would write %s (%zu bytes):\n",
                   FSTAB_PATH, content_len);
            printf("%s", content);
            printf("fstab: [dry-run] would run `swapon -a` and `mount -a`\n");
        } else {
            printf("fstab: [dry-run] no changes (content matches existing "
                   "/etc/fstab)\n");
        }
        free(content);
        free(existing);
        return 0;
    }

    if (!changed) {
        printf("fstab: no changes (content matches existing /etc/fstab)\n");
        free(content);
        free(existing);
        return 0;
    }

    if (existing) {
        FILE *bak = fopen(FSTAB_BAK_PATH, "w");
        if (!bak) {
            fprintf(stderr, "fstab: cannot write backup %s: %s\n",
                    FSTAB_BAK_PATH, strerror(errno));
            free(content);
            free(existing);
            return 1;
        }
        fputs(existing, bak);
        fclose(bak);
        printf("fstab: backed up existing /etc/fstab to %s\n",
               FSTAB_BAK_PATH);
    }

    char tmp_path[] = "/etc/fstab.2O9.tmp.XXXXXX";
    int fd = mkstemp(tmp_path);
    if (fd < 0) {
        fprintf(stderr, "fstab: mkstemp failed: %s\n", strerror(errno));
        free(content);
        free(existing);
        return 1;
    }
    if (write(fd, content, content_len) != (ssize_t)content_len) {
        fprintf(stderr, "fstab: write failed: %s\n", strerror(errno));
        close(fd);
        unlink(tmp_path);
        free(content);
        free(existing);
        return 1;
    }
    close(fd);
    if (rename(tmp_path, FSTAB_PATH) != 0) {
        fprintf(stderr, "fstab: rename %s -> %s failed: %s\n",
                tmp_path, FSTAB_PATH, strerror(errno));
        unlink(tmp_path);
        free(content);
        free(existing);
        return 1;
    }
    chmod(FSTAB_PATH, 0644);
    printf("fstab: wrote %s (%zu bytes)\n", FSTAB_PATH, content_len);

    /* Activate swap and mount new entries. mount -a does NOT remount
     * already-mounted filesystems, so option changes need a reboot. */
    printf("fstab: running `swapon -a` and `mount -a`\n");
    const char *swapon_argv[] = {"swapon", "-a", NULL};
    int rc1 = run_cmd(swapon_argv);
    if (rc1 != 0)
        fprintf(stderr, "fstab: swapon -a exited %d\n", rc1);
    const char *mount_argv[] = {"mount", "-a", NULL};
    int rc2 = run_cmd(mount_argv);
    if (rc2 != 0)
        fprintf(stderr, "fstab: mount -a exited %d\n", rc2);
    printf("fstab: already-mounted file systems were not remounted; "
           "reboot for option changes to take effect\n");

    free(content);
    free(existing);
    return 0;
}
