/* pam_nss.c - declarative PAM and NSS configuration (Phase 4)
 *
 * Applies the `security.pam` and `security.nss` blocks from a 2O9 manifest.
 * PAM service configs go to /etc/pam.d/<service>; NSS sources go to
 * /etc/nsswitch.conf. Each existing file is backed up to <path>.bak.2O9
 * (single most-recent backup) before the new content is written.
 *
 * PAM services support two forms:
 *   - string form: the value is the full PAM config text. Written verbatim.
 *   - structured form: an attrset with `auth`, `account`, `password`,
 *     `session` keys. Each is a list of {type, control, args} entries.
 *     2O9 renders the lines.
 *
 * NSS databases map directly to /etc/nsswitch.conf lines. Each value is a
 * list of sources. A source can be a string ("files") or a sublist whose
 * first element is the source name and the rest are action specifiers
 * (e.g. [ "dns" "UNAVAIL=continue" ] -> "dns [UNAVIL=continue]").
 *
 * Removal: if prev_manifest_json is non-NULL and had PAM services no
 * longer in the current manifest, 2O9 prints a warning naming the service
 * and the file path. The file is NOT removed; the user handles that.
 *
 * Permissions: writes to /etc/pam.d/ and /etc/nsswitch.conf require root.
 * pam_nss_apply checks getuid() == 0 and returns an error otherwise.
 *
 * PAM reads /etc/pam.d/ on every auth call, so no reload is needed after
 * writing.
 *
 * The Makefile passes -D_GNU_SOURCE; open_memstream / asprintf / strdup
 * are available because of that.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <errno.h>
#include <limits.h>

#include "pam_nss.h"
#include "cJSON.h"

#define PAM_DIR          "/etc/pam.d"
#define NSS_PATH         "/etc/nsswitch.conf"
#define NSS_BAK_PATH     "/etc/nsswitch.conf.bak.2O9"
#define TWO9_HEADER      "# Generated by 2O9. Do not edit; run `209 apply` to regenerate.\n"

/* PAM facility names in canonical output order. */
static const char * const PAM_FACILITIES[] = { "auth", "account", "password", "session" };
#define PAM_FACILITY_COUNT (sizeof(PAM_FACILITIES) / sizeof(PAM_FACILITIES[0]))

/* ── File helpers ──────────────────────────────────────────────────── */

/* Read an entire file into a malloc'd buffer. Returns NULL if the file
 * does not exist or cannot be read. Caller frees. */
static char *read_file(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f) return NULL;
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return NULL; }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return NULL; }
    rewind(f);
    char *buf = malloc((size_t)sz + 1);
    if (!buf) { fclose(f); return NULL; }
    size_t n = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    buf[n] = '\0';
    return buf;
}

/* mkdir -p. Returns 0 on success or if path already exists. */
static int mkdir_p(const char *path)
{
    char tmp[PATH_MAX];
    snprintf(tmp, sizeof(tmp), "%s", path);
    size_t len = strlen(tmp);
    if (len == 0) return -1;
    if (tmp[len - 1] == '/') tmp[len - 1] = '\0';
    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = '\0';
            if (mkdir(tmp, 0755) < 0 && errno != EEXIST) return -1;
            *p = '/';
        }
    }
    if (mkdir(tmp, 0755) < 0 && errno != EEXIST) return -1;
    return 0;
}

/* Copy src_path to dst_path. Returns 0 on success, non-zero on error. */
static int copy_file(const char *src_path, const char *dst_path)
{
    char *content = read_file(src_path);
    if (!content) return -1;
    size_t len = strlen(content);
    FILE *out = fopen(dst_path, "w");
    if (!out) { free(content); return -1; }
    size_t w = fwrite(content, 1, len, out);
    fclose(out);
    free(content);
    return (w == len) ? 0 : -1;
}

/* Write a file atomically via mkstemp + rename. The temp file is created
 * in the same directory as the target so rename works. */
static int write_file_atomic(const char *path, const char *content,
                             size_t len, mode_t mode)
{
    char tmp_path[PATH_MAX];
    int n = snprintf(tmp_path, sizeof(tmp_path), "%s.2O9.tmp.XXXXXX", path);
    if (n < 0 || (size_t)n >= sizeof(tmp_path)) {
        fprintf(stderr, "pam_nss: path too long for temp: %s\n", path);
        return -1;
    }
    int fd = mkstemp(tmp_path);
    if (fd < 0) {
        fprintf(stderr, "pam_nss: mkstemp for %s failed: %s\n",
                path, strerror(errno));
        return -1;
    }
    if (write(fd, content, len) != (ssize_t)len) {
        fprintf(stderr, "pam_nss: write to %s failed: %s\n",
                path, strerror(errno));
        close(fd);
        unlink(tmp_path);
        return -1;
    }
    close(fd);
    if (chmod(tmp_path, mode) != 0) {
        /* non-fatal: file is written, mode may be wrong */
    }
    if (rename(tmp_path, path) != 0) {
        fprintf(stderr, "pam_nss: rename %s -> %s failed: %s\n",
                tmp_path, path, strerror(errno));
        unlink(tmp_path);
        return -1;
    }
    return 0;
}

/* Back up an existing file to <path>.bak.2O9. Silent if the file does
 * not exist. Returns 0 on success or no-op, non-zero on copy error. */
static int backup_existing(const char *path, const char *bak_path)
{
    struct stat st;
    if (stat(path, &st) != 0) return 0; /* nothing to back up */
    if (copy_file(path, bak_path) != 0) {
        fprintf(stderr, "pam_nss: failed to back up %s to %s: %s\n",
                path, bak_path, strerror(errno));
        return -1;
    }
    printf("pam_nss: backed up existing %s to %s\n", path, bak_path);
    return 0;
}

/* ── PAM service name validation ───────────────────────────────────── */

/* Reject names that could escape /etc/pam.d/. A valid PAM service name
 * contains no '/' and no ".." segment. Returns 0 if valid, non-zero
 * otherwise. */
static int pam_service_name_ok(const char *name)
{
    if (!name || !*name) return 0;
    if (strchr(name, '/')) return 0;
    /* Reject any literal ".." (path-traversal segment). */
    if (strstr(name, "..")) return 0;
    return 1;
}

/* ── PAM structured rendering ──────────────────────────────────────── */

/* Render a single PAM facility section into mem. facility is one of
 * "auth", "account", "password", "session". entries is the cJSON array
 * of {type, control, args} objects. Returns 0 on success, non-zero on
 * a hard rendering error. Malformed entries are skipped with a warning. */
static int render_pam_facility(FILE *mem, const char *facility, cJSON *entries)
{
    if (!entries || !cJSON_IsArray(entries)) return 0;
    cJSON *entry;
    cJSON_ArrayForEach(entry, entries) {
        if (!cJSON_IsObject(entry)) {
            fprintf(stderr, "pam_nss: skipping non-object %s entry\n",
                    facility);
            continue;
        }
        cJSON *type = cJSON_GetObjectItem(entry, "type");
        cJSON *ctrl = cJSON_GetObjectItem(entry, "control");
        if (!cJSON_IsString(type) || !cJSON_IsString(ctrl)) {
            fprintf(stderr, "pam_nss: skipping malformed %s entry "
                    "(type and control required)\n", facility);
            continue;
        }
        fprintf(mem, "%-12s%-12s%s", facility, type->valuestring,
                ctrl->valuestring);
        cJSON *args = cJSON_GetObjectItem(entry, "args");
        if (args && cJSON_IsArray(args)) {
            cJSON *arg;
            cJSON_ArrayForEach(arg, args) {
                if (cJSON_IsString(arg) && arg->valuestring[0] != '\0')
                    fprintf(mem, " %s", arg->valuestring);
            }
        }
        fputc('\n', mem);
    }
    return 0;
}

/* Render a structured PAM service config into a malloc'd string.
 * Returns NULL on OOM. Caller frees. */
static char *render_pam_structured(cJSON *svc)
{
    char *buf = NULL;
    size_t len = 0;
    FILE *mem = open_memstream(&buf, &len);
    if (!mem) return NULL;
    fputs(TWO9_HEADER, mem);
    for (size_t i = 0; i < PAM_FACILITY_COUNT; i++) {
        cJSON *fac = cJSON_GetObjectItem(svc, PAM_FACILITIES[i]);
        if (fac) render_pam_facility(mem, PAM_FACILITIES[i], fac);
    }
    fclose(mem);
    return buf;
}

/* ── PAM apply ─────────────────────────────────────────────────────── */

/* Apply the security.pam block. Returns 0 on success, non-zero on error. */
static int apply_pam(cJSON *root, cJSON *prev_root, int dry_run)
{
    cJSON *pam = cJSON_GetObjectItem(root, "security");
    if (pam) pam = cJSON_GetObjectItem(pam, "pam");
    if (!pam || !cJSON_IsObject(pam)) {
        printf("pam_nss: no security.pam block; skipping PAM\n");
        return 0;
    }
    /* Empty object: skip. cJSON_GetArraySize on an object counts members. */
    if (cJSON_GetArraySize(pam) == 0) {
        printf("pam_nss: security.pam is empty; skipping PAM\n");
        return 0;
    }

    if (!dry_run && mkdir_p(PAM_DIR) != 0) {
        fprintf(stderr, "pam_nss: cannot create %s: %s\n",
                PAM_DIR, strerror(errno));
        return 1;
    }

    /* Iterate over declared services. */
    cJSON *svc;
    cJSON_ArrayForEach(svc, pam) {
        const char *name = svc->string;
        if (!name || !*name) continue;
        if (!pam_service_name_ok(name)) {
            fprintf(stderr, "pam_nss: rejecting PAM service name '%s' "
                    "(contains '/' or '..')\n", name);
            return 1;
        }

        char path[PATH_MAX], bak_path[PATH_MAX];
        int plen = snprintf(path, sizeof(path), "%s/%s", PAM_DIR, name);
        if (plen < 0 || (size_t)plen >= sizeof(path)) {
            fprintf(stderr, "pam_nss: PAM service path too long: %s/%s\n",
                    PAM_DIR, name);
            return 1;
        }
        int blen = snprintf(bak_path, sizeof(bak_path), "%s.bak.2O9", path);
        if (blen < 0 || (size_t)blen >= sizeof(bak_path)) {
            fprintf(stderr, "pam_nss: PAM backup path too long: %s\n", path);
            return 1;
        }

        char *content = NULL;
        if (cJSON_IsString(svc)) {
            /* Verbatim form: prepend the 2O9 header so the file is
             * self-identifying. The user's text follows unchanged. */
            size_t hlen = strlen(TWO9_HEADER);
            size_t blen = strlen(svc->valuestring);
            content = malloc(hlen + blen + 1);
            if (!content) {
                fprintf(stderr, "pam_nss: out of memory\n");
                return 1;
            }
            memcpy(content, TWO9_HEADER, hlen);
            memcpy(content + hlen, svc->valuestring, blen);
            content[hlen + blen] = '\0';
        } else if (cJSON_IsObject(svc)) {
            content = render_pam_structured(svc);
            if (!content) {
                fprintf(stderr, "pam_nss: failed to render PAM service "
                        "'%s'\n", name);
                return 1;
            }
        } else {
            fprintf(stderr, "pam_nss: skipping PAM service '%s' (value is "
                    "neither string nor object)\n", name);
            continue;
        }

        size_t content_len = strlen(content);

        if (dry_run) {
            printf("pam_nss: [dry-run] would write %s (%zu bytes):\n",
                   path, content_len);
            printf("%s", content);
            free(content);
            continue;
        }

        if (backup_existing(path, bak_path) != 0) {
            free(content);
            return 1;
        }
        if (write_file_atomic(path, content, content_len, 0644) != 0) {
            free(content);
            return 1;
        }
        printf("pam_nss: wrote %s (%zu bytes)\n", path, content_len);
        free(content);
    }

    /* Warn about removed services. */
    if (prev_root) {
        cJSON *prev_sec = cJSON_GetObjectItem(prev_root, "security");
        cJSON *prev_pam = prev_sec ? cJSON_GetObjectItem(prev_sec, "pam") : NULL;
        if (prev_pam && cJSON_IsObject(prev_pam)) {
            cJSON *prev_svc;
            cJSON_ArrayForEach(prev_svc, prev_pam) {
                const char *name = prev_svc->string;
                if (!name || !*name) continue;
                if (cJSON_GetObjectItem(pam, name) == NULL) {
                    fprintf(stderr, "pam_nss: WARNING PAM service '%s' no "
                            "longer declared (was at %s/%s); leaving file "
                            "in place, remove manually if desired\n",
                            name, PAM_DIR, name);
                }
            }
        }
    }

    return 0;
}

/* ── NSS rendering ─────────────────────────────────────────────────── */

/* Render a single NSS source element into mem. The element is either a
 * string (the source name) or an array whose first element is the source
 * name and the rest are action specifiers. */
static void render_nss_source(FILE *mem, cJSON *src)
{
    if (cJSON_IsString(src)) {
        fputs(src->valuestring, mem);
        return;
    }
    if (!cJSON_IsArray(src)) return;

    cJSON *first = cJSON_GetArrayItem(src, 0);
    if (!first || !cJSON_IsString(first)) return;
    fputs(first->valuestring, mem);

    int n = cJSON_GetArraySize(src);
    if (n <= 1) {
        /* Single-element sublist: default action. */
        fputs(" [NOTFOUND=return]", mem);
        return;
    }
    fputs(" [", mem);
    for (int i = 1; i < n; i++) {
        cJSON *act = cJSON_GetArrayItem(src, i);
        if (cJSON_IsString(act) && act->valuestring[0] != '\0') {
            if (i > 1) fputc(' ', mem);
            fputs(act->valuestring, mem);
        }
    }
    fputc(']', mem);
}

/* Apply the security.nss block. Returns 0 on success, non-zero on error. */
static int apply_nss(cJSON *root, int dry_run)
{
    cJSON *nss = cJSON_GetObjectItem(root, "security");
    if (nss) nss = cJSON_GetObjectItem(nss, "nss");
    if (!nss || !cJSON_IsObject(nss)) {
        printf("pam_nss: no security.nss block; skipping NSS\n");
        return 0;
    }
    if (cJSON_GetArraySize(nss) == 0) {
        printf("pam_nss: security.nss is empty; skipping NSS\n");
        return 0;
    }

    char *content = NULL;
    size_t content_len = 0;
    FILE *mem = open_memstream(&content, &content_len);
    if (!mem) {
        fprintf(stderr, "pam_nss: open_memstream failed\n");
        return 1;
    }
    fputs(TWO9_HEADER, mem);

    cJSON *db;
    cJSON_ArrayForEach(db, nss) {
        const char *name = db->string;
        if (!name || !*name) continue;
        if (!cJSON_IsArray(db)) {
            fprintf(stderr, "pam_nss: skipping NSS database '%s' (value is "
                    "not a list)\n", name);
            continue;
        }
        fprintf(mem, "%s:", name);
        cJSON *src;
        cJSON_ArrayForEach(src, db) {
            fputc(' ', mem);
            render_nss_source(mem, src);
        }
        fputc('\n', mem);
    }
    fclose(mem);

    if (dry_run) {
        printf("pam_nss: [dry-run] would write %s (%zu bytes):\n",
               NSS_PATH, content_len);
        printf("%s", content);
        free(content);
        return 0;
    }

    if (backup_existing(NSS_PATH, NSS_BAK_PATH) != 0) {
        free(content);
        return 1;
    }
    if (write_file_atomic(NSS_PATH, content, content_len, 0644) != 0) {
        free(content);
        return 1;
    }
    printf("pam_nss: wrote %s (%zu bytes)\n", NSS_PATH, content_len);
    free(content);
    return 0;
}

/* ── Main entry point ──────────────────────────────────────────────── */

int pam_nss_apply(const char *manifest_json, const char *prev_manifest_json,
                  int dry_run)
{
    if (getuid() != 0) {
        fprintf(stderr, "pam_nss: must run as root (writes /etc/pam.d/ and "
                "/etc/nsswitch.conf)\n");
        return 1;
    }
    if (!manifest_json) {
        fprintf(stderr, "pam_nss: manifest_json is NULL\n");
        return 1;
    }

    cJSON *root = cJSON_Parse(manifest_json);
    if (!root) {
        fprintf(stderr, "pam_nss: failed to parse manifest JSON\n");
        return 1;
    }
    cJSON *prev_root = NULL;
    if (prev_manifest_json) {
        prev_root = cJSON_Parse(prev_manifest_json);
        /* NULL is OK; we just skip the prev comparison. */
    }

    int rc = apply_pam(root, prev_root, dry_run);
    if (rc == 0) rc = apply_nss(root, dry_run);

    cJSON_Delete(root);
    cJSON_Delete(prev_root);
    return rc;
}
