/* pgp.c - PGP key auto-import implementation
 *
 * Parses .SRCINFO (generated by `makepkg --printsrcinfo`) for
 * `validpgpkeys = <fingerprint>` lines. For each missing key, prompts
 * the user (y/N) and imports via `gpg --recv-keys`.
 *
 * Modeled on paru's src/keys.rs.
 *
 * .SRCINFO format (relevant excerpt):
 *   pkgbase = foo
 *   pkgver = 1.0-1
 *   ...
 *   validpgpkeys = ABCDEF1234567890...
 *   validpgpkeys = FEDCBA0987654321...
 *
 * Multiple keys appear as multiple lines with the same key, not as a
 * space-separated list. We collect them all.
 */

/* _GNU_SOURCE is provided by the Makefile (-D_GNU_SOURCE). */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <limits.h>
#include <ctype.h>
#include <spawn.h>
#include <sys/wait.h>
#include <fcntl.h>

extern char **environ;

#include "pgp.h"

/* ── Helpers ──────────────────────────────────────────────────────── */

static char *str_trim(char *s)
{
        while (*s && isspace((unsigned char)*s)) s++;
        if (!*s) return s;
        char *end = s + strlen(s) - 1;
        while (end > s && isspace((unsigned char)*end)) {
                *end = '\0';
                end--;
        }
        return s;
}

/* Run a command, redirect stdout to a file. Returns 0 on success. */
static int run_to_file(char **argv, const char *outfile)
{
        pid_t pid;
        posix_spawn_file_actions_t actions;
        posix_spawn_file_actions_init(&actions);

        int fd = open(outfile, O_WRONLY | O_CREAT | O_TRUNC, 0644);
        if (fd < 0) {
                posix_spawn_file_actions_destroy(&actions);
                return -1;
        }
        posix_spawn_file_actions_adddup2(&actions, fd, STDOUT_FILENO);
        posix_spawn_file_actions_addclose(&actions, fd);

        int ret = posix_spawnp(&pid, argv[0], &actions, NULL, argv, environ);
        posix_spawn_file_actions_destroy(&actions);

        if (ret != 0) {
                close(fd);
                return -1;
        }
        close(fd);

        int status;
        waitpid(pid, &status, 0);

        return WIFEXITED(status) && WEXITSTATUS(status) == 0 ? 0 : -1;
}

/* Generate .SRCINFO in clone_dir if missing via `makepkg --printsrcinfo`.
 * Returns 0 on success or already-present, -1 on failure. */
static int ensure_srcinfo(const char *clone_dir)
{
        char srcinfo_path[PATH_MAX];
        snprintf(srcinfo_path, sizeof(srcinfo_path), "%s/.SRCINFO", clone_dir);

        struct stat st;
        if (stat(srcinfo_path, &st) == 0)
                return 0;  /* already exists */

        char *argv[] = { "makepkg", "--printsrcinfo", NULL };

        int saved_cwd = open(".", O_RDONLY);
        if (saved_cwd < 0) return -1;
        if (chdir(clone_dir) < 0) {
                close(saved_cwd);
                return -1;
        }

        int rc = run_to_file(argv, srcinfo_path);

        fchdir(saved_cwd);
        close(saved_cwd);

        return rc;
}

/* ── Public API ──────────────────────────────────────────────────── */

char **pgp_read_valid_keys(const char *clone_dir)
{
        if (!clone_dir) return NULL;

        if (ensure_srcinfo(clone_dir) < 0) {
                fprintf(stderr,
                        "  warning: could not generate .SRCINFO for PGP key check\n");
                return NULL;
        }

        char srcinfo_path[PATH_MAX];
        snprintf(srcinfo_path, sizeof(srcinfo_path), "%s/.SRCINFO", clone_dir);

        FILE *f = fopen(srcinfo_path, "r");
        if (!f) return NULL;

        size_t cap = 8, count = 0;
        char **keys = calloc(cap, sizeof(char *));

        char line[4096];
        const char *prefix = "validpgpkeys = ";

        while (fgets(line, sizeof(line), f)) {
                char *nl = strchr(line, '\n');
                if (nl) *nl = '\0';

                /* Find "validpgpkeys = " anywhere on the line */
                char *p = strstr(line, prefix);
                if (!p) continue;

                char *val = p + strlen(prefix);
                val = str_trim(val);
                if (*val == '\0') continue;

                if (count >= cap) {
                        cap *= 2;
                        keys = realloc(keys, cap * sizeof(char *));
                }
                keys[count++] = strdup(val);
        }
        fclose(f);

        if (count == 0) {
                free(keys);
                return NULL;
        }

        /* NULL-terminate (cap is at least count+1 because we doubled
         * whenever count met cap; verify by extending if needed) */
        if (count >= cap) {
                cap += 1;
                keys = realloc(keys, cap * sizeof(char *));
        }
        keys[count] = NULL;

        return keys;
}

char **pgp_find_missing(char **keys)
{
        if (!keys) return NULL;

        size_t cap = 8, count = 0;
        char **missing = calloc(cap, sizeof(char *));

        for (size_t i = 0; keys[i]; i++) {
                /* gpg --list-keys exits 0 if key is in keyring, non-zero otherwise */
                char cmd[512];
                snprintf(cmd, sizeof(cmd),
                         "gpg --list-keys '%s' >/dev/null 2>&1", keys[i]);
                int rc = system(cmd);
                if (rc != 0) {
                        if (count >= cap) {
                                cap *= 2;
                                missing = realloc(missing, cap * sizeof(char *));
                        }
                        missing[count++] = strdup(keys[i]);
                }
        }

        if (count == 0) {
                free(missing);
                return NULL;
        }

        if (count >= cap) {
                cap += 1;
                missing = realloc(missing, cap * sizeof(char *));
        }
        missing[count] = NULL;

        return missing;
}

int pgp_import_missing(char **missing)
{
        if (!missing) return 0;

        /* Check if gpg is installed */
        if (system("gpg --version >/dev/null 2>&1") != 0) {
                fprintf(stderr,
                        "  warning: gpg not installed; cannot import PGP keys\n");
                fprintf(stderr,
                        "  the build will fail at `makepkg --verifysource`\n");
                return -1;
        }

        for (size_t i = 0; missing[i]; i++) {
                fprintf(stderr, "  missing PGP key: %s\n", missing[i]);
                fprintf(stderr, "  import via gpg --recv-keys? [y/N] ");
                fflush(stderr);

                char buf[8];
                if (!fgets(buf, sizeof(buf), stdin)) {
                        fprintf(stderr,
                                "  declined; build will fail at source verification\n");
                        return -1;
                }

                if (buf[0] != 'y' && buf[0] != 'Y') {
                        fprintf(stderr,
                                "  declined; build will fail at `makepkg --verifysource`\n");
                        return -1;
                }

                char cmd[512];
                snprintf(cmd, sizeof(cmd), "gpg --recv-keys '%s'", missing[i]);
                if (system(cmd) != 0) {
                        fprintf(stderr,
                                "  gpg --recv-keys failed for %s\n", missing[i]);
                        return -1;
                }
        }

        return 0;
}

void pgp_free_list(char **list)
{
        if (!list) return;
        for (size_t i = 0; list[i]; i++)
                free(list[i]);
        free(list);
}
